---
title: "data_viz_2"
author: "Kimia Faroughi"
date: "2025-09-30"
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(p8105.datasets)
library(ggridges)
library(viridis)
```

```{r}
data("weather_df")
```

Let's make our basic scatterplot.

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.5) +
  labs(
    x = "Minimum daily temp",
    y = "Maximum daily temp",
    title = "Temperature scatterplot",
    caption = "Data from NOAA",
    color = "Location"
  )
```

## Scales

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.5) +
  labs(
    x = "Minimum daily temp",
    y = "Maximum daily temp",
    title = "Temperature scatterplot",
    caption = "Data from NOAA",
    color = "Location"
  ) +
  scale_x_continuous(
    breaks = c(-20, 0, 25),
    labels = c("-20C", "0", "25")
  ) +
  scale_y_continuous(
    trans = "sqrt",
    limits = c(10, 30)
  ) + #can also filter the data at the beginning so that tmax > 10 and < 30
  viridis::scale_color_viridis(
    discrete = TRUE
  ) #package creates friendly color palette (don't create your own)
```

